home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

league_view/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^matchhistory/', include('match_history.urls')),
    url(r'^admin/', admin.site.urls),
]

match_history/urls.py
from django.conf.urls import url
from . import views

app_name = 'match_history'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search_summoner/$', views.search_summoner, name='search_summoner'),
    url(r'^(?P<game_id>[0-9]+)/$', views.detail, name='detail')
]

home/models.py
from django.db import models

# Create your models here.

match_history/models.py
from django.db import models


class Account(models.Model):
    account_id = models.IntegerField()
    summoner_name = models.CharField(max_length=250)
    profile_icon_id = models.IntegerField()
    summoner_level = models.IntegerField()

    def __str__(self):
        return self.summoner_name + " - " + str(self.account_id)

    def get_account_id(self):
        return self.account_id



class Match(models.Model):
    game_id = models.IntegerField()
    mode = models.CharField(max_length=30, null=True)

    # can determine red teams also
    blue_team_win = models.CharField(max_length=10)
    blue_team_first_blood = models.NullBooleanField()
    blue_team_first_tower = models.NullBooleanField()
    blue_team_first_inhib = models.NullBooleanField()
    blue_team_first_baron = models.NullBooleanField()
    blue_team_first_herald = models.NullBooleanField()

    # blue team details
    blue_team_id = models.IntegerField(null=True)
    blue_team_baron_kills = models.IntegerField(null=True)
    blue_team_dragon_kills = models.IntegerField(null=True)
    blue_team_tower_kills = models.IntegerField(null=True)
    blue_team_rift_herald = models.IntegerField(null=True)
    blue_team_ban1 = models.IntegerField(null=True)
    blue_team_ban2 = models.IntegerField(null=True)
    blue_team_ban3 = models.IntegerField(null=True)
    blue_team_ban4 = models.IntegerField(null=True)
    blue_team_ban5 = models.IntegerField(null=True)

    # red team details
    red_team_id = models.IntegerField(null=True)
    red_team_baron_kills = models.IntegerField(null=True)
    red_team_dragon_kills = models.IntegerField(null=True)
    red_team_tower_kills = models.IntegerField(null=True)
    red_team_rift_herald = models.IntegerField(null=True)
    red_team_ban1 = models.IntegerField(null=True)
    red_team_ban2 = models.IntegerField(null=True)
    red_team_ban3 = models.IntegerField(null=True)
    red_team_ban4 = models.IntegerField(null=True)
    red_team_ban5 = models.IntegerField(null=True)

    def __str__(self):
        return str(self.game_id)


class Player(models.Model):

    # summoner stats
    participant_id = models.IntegerField()
    team_id = models.IntegerField()
    game_id = models.IntegerField()
    champion_id = models.IntegerField()
    summoner1_id = models.IntegerField()
    summoner2_id = models.IntegerField()
    summoner_id = models.IntegerField(null=True)

    # gameplay stats
    item0 = models.IntegerField(null=True)
    item1 = models.IntegerField(null=True)
    item2 = models.IntegerField(null=True)
    item3 = models.IntegerField(null=True)
    item4 = models.IntegerField(null=True)
    item5 = models.IntegerField(null=True)
    item6 = models.IntegerField(null=True)
    kills = models.IntegerField(null=True)
    deaths = models.IntegerField(null=True)
    assists = models.IntegerField(null=True)
    largest_killing_spree = models.IntegerField(null=True)
    largest_multi_kill = models.IntegerField(null=True)
    double_kills = models.IntegerField(null=True)
    triple_kills = models.IntegerField(null=True)
    quadra_kills = models.IntegerField(null=True)
    penta_kills = models.IntegerField(null=True)

    def __str__(self):
        return str(self.game_id) + " - " + str(self.participant_id)

home/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'home/index.html')

match_history/views.py
from django.shortcuts import render
from .LeagueParser import MatchHistoryParser, AccountParser
from .models import Account, Player, Match
from LeagueAPI.MatchTool import MatchTool


# Create your views here.


def index(request):
    data = {}
    return render(request, 'match_history/index.html', data)


def detail(request, game_id):
    test = MatchTool('RGAPI-5ed59bd7-1a5c-4c8e-a645-c3ce4c875f64', 'na1')
    test.save_match(game_id, '212268870')
    return render(request, 'match_history/match_details.html')


def search_summoner(request):
    summoner_name = request.POST.get('summoner_name', '').lower()
    try:
        try_summoner = Account.objects.get(summoner_name=summoner_name)
    except Account.DoesNotExist:
        # add the user that was not found to the database.
        account_parser = AccountParser('RGAPI-5ed59bd7-1a5c-4c8e-a645-c3ce4c875f64', 'na1')
        account_parser.get_account_by_summoner_name(request.POST['summoner_name'])
        # get the user that was just added to the database to get their match history
        searched_summoner = Account.objects.get(summoner_name=summoner_name)
        match_parser = MatchHistoryParser('RGAPI-5ed59bd7-1a5c-4c8e-a645-c3ce4c875f64', 'na1')
        match_parser.get_match_history(searched_summoner.get_account_id())
        match_history = match_parser.convert_match_data()
        data = {
            'summoner': searched_summoner,
            'match_history': match_history
        }
        return render(request, 'match_history/index.html', data)
    except KeyError:
        return render(request, 'match_history/index.html', {
            "error_message": "There have been an error searching of that summoner"
        })
    else:
        searched_summoner = Account.objects.get(summoner_name=summoner_name)
        match_parser = MatchHistoryParser('RGAPI-5ed59bd7-1a5c-4c8e-a645-c3ce4c875f64', 'na1')
        match_parser.get_match_history(searched_summoner.get_account_id())
        match_history = match_parser.convert_match_data()
        data = {
            'summoner': searched_summoner,
            'match_history': match_history
        }
        return render(request, 'match_history/index.html', data)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}League View{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" >
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:index' %}">League View</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'match_history:index' %}">
                            <span class="glyphicon glyphicon-user"></span> Summoners
                        </a>
                    </li>
                    <li class="">
                        <a href="#">Champions</a>
                    </li>
                </ul>


                <form class="navbar-form navbar-left" role="search" method="post" action="{% url 'match_history:search_summoner' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="summoner_name" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block title %}
    League View
{% endblock %}

{% block body %}
    <div class="row">
        <h1 class="home-title, col-md-offset-4">Welcome to League View</h1>
    </div>
{% endblock %}

match_history/templates/match_history/index.html
{% extends 'home/base.html' %}

{% block body %}

    {% if summoner %}
    <div class="container-fluid">
        <h2>{{ summoner.summoner_name }}</h2>
        <img src="http://ddragon.leagueoflegends.com/cdn/6.24.1/img/profileicon/{{ summoner.profile_icon_id }}.png" />
        <p>{{ summoner.summoner_level }}</p>
    </div>
    {% endif %}


    {% if match_history %}
        <h2>Match History</h2>
        {% for match in match_history %}
            <h3>
                Champion -
                <img height="25px" width="25px" src="http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/{{ match.championName }}.png" />
                <a href="{% url 'match_history:detail' match.gameId %}" >{{ match.championName }} </a> - ({{ match.lane }})
            </h3>
            <h4>Date - {{ match.timestamp }}</h4><br>
        {% endfor %}
    {% endif %}
{% endblock %}

match_history/templates/match_history/match_details.html
{% extends 'home/base.html' %}
{% block title %}
    Match-{{ match_info }}
{% endblock %}

{% block body %}

<h2>Match - {{ match_info }}</h2>
<h2>Blue Team</h2>
<ul>
    <li>win - {{ blue_team.win }}</li>
    <li>firstBlood  - {{ blue_team.firstBlood }}</li>
    <li>firstTower  - {{ blue_team.firstTower }}</li>
    <li>firstBaron  - {{ blue_team.firstBaron }}</li>
    <li>firstDragon  - {{ blue_team.firstDragon }}</li>
    <li>towerKills  - {{ blue_team.towerKills }}</li>
</ul>
<h2>Red Team</h2>
<ul>
    <li>win  - {{ red_team.win }}</li>
    <li>firstBlood  - {{ red_team.firstBlood }}</li>
    <li>firstTower  - {{ red_team.firstTower }}</li>
    <li>firstBaron  - {{ red_team.firstBaron }}</li>
    <li>firstDragon  - {{ red_team.firstDragon }}</li>
    <li>towerKills  - {{ red_team.towerKills }}</li>
</ul>

{% endblock %}